import type { Metadata } from "next";
import { Grandstander } from "next/font/google";
import "./globals.css";
import "./style.css"

const grandstander = Grandstander({
    variable: "--font-grandstander",
    // Medium, Bold, Black
    weight: ["500", "700", "900"],
    subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${grandstander.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
